# Generated by Django 5.0 on 2026-05-30 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='payout_method',
            field=models.CharField(choices=[('opay', 'OPay'), ('palmpay', 'PalmPay'), ('bank_transfer', 'Bank Transfer'), ('cash_agent', 'Cash Agent')], default='opay', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='ai_insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_insight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_remaining', models.IntegerField(default=14)),
                ('start_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='App.advancerequest')),
            ],
        ),
    ]
